DELETE FROM category;
INSERT INTO category (name) VALUES ('Produce');
INSERT INTO category (name) VALUES ('Beverages');
INSERT INTO category (name) VALUES ('Bread & Bakery');
INSERT INTO category (name) VALUES ('Canned & Jarred Goods');
INSERT INTO category (name) VALUES ('Condiments, Spices & Baking');
INSERT INTO category (name) VALUES ('Dairy, Eggs & Cheese');
INSERT INTO category (name) VALUES ('Grains, Pasta & Cereal');
INSERT INTO category (name) VALUES ('Frozen Foods');
INSERT INTO category (name) VALUES ('Meat & Seafood');
INSERT INTO category (name) VALUES ('Sauces & Oils');
INSERT INTO category (name) VALUES ('Snacks & Candy');
INSERT INTO category (name) VALUES ('Personal & Health Care');
INSERT INTO category (name) VALUES ('Household & Cleaning Supplies');
INSERT INTO category (name) VALUES ('Other');